INSERT INTO department	( department_name			)
VALUES					('Marketing'				),
						('Sales'					),
						('Sercurity'				),
						('Technical'				),
						('Accounting '				),
						('Director'					),
						('Audit'					),
						('Purchasing'				),
						('Training'					),
						('Administration'			),
						('HR'						),
						('Customer Service'			),
						('Vice director'			),
						('IT'						),
						('IT help desk'				),
						('International Payment'	),
						('Financial'				),
						('International Relations'	),
						('Local Payment'			),
						('Pulic Relations'			);

INSERT INTO `position`	(position_name	)  
VALUES					('Dev'		  	),
						('Test'		  	),
                        ('Scrum Master'	),
                        ('PM'     		);
                        
INSERT INTO `account`	(		email,				 				username, 					fullname, 				department_id, 			position_id, 				created_date				)
VALUES					( 		'thuy.ptt@gmail.com',			'thuy.phamthithanh',		'Phạm Thị Thanh Thủy', 			2,						2,					 	'2018-08-01'				),
						( 		'tvd@gmail.com',				'thuan.vuduc',				'Vũ Đức Thuận',					3, 						4, 					 	 NULL						),
                        ( 		'hanhhong1999@gmail.com',		'hanh.nguyenhong',			'Nguyễn Hồng Hạnh',				4,						4,					 	 NULL     					),
                        ( 		'hienthu.13@gmail.com',			'hien.nguyenthithu',		'Nguyễn Thi	Thu Hiền',			5, 						3,						'2017-08-08'				),
                        (		'keefe@gmail.com',				'ashton.tillman',			'Dr. Mckenna Jacobson Sr.',		8,						2,			     	 	'2010-10-14 03:35:23'		),
                        (		'eldred.sporer@gmail.com',		'eweber.sporer',			'Marie Marvin',					15,						3,					 	'2018-04-07 16:47:12'		),
						(		'maxie.koch@gmail.com',			'fahey.demarco',			'Prof. Edgardo Bergnaum',		9,						4,					  	NULL						),
						(		'tierra.lind@gmail.com',		'alberta61',				'Alyson Schaden',				1,						3,					  	'2010-04-12 06:35:47'		),
						(		'laila32@gmail.com',			'ypouros',					'Mr. Chadrick Cassin V',		20,						4,					  	'2018-07-10 19:41:26'		),
						(		'daron78@gmail.com',			'owen00',					'Kenyatta Bernhard',			5,						4,						'2000-10-03 05:24:09'		),
						(		'walter.mauricio@gmail.com',	'roberskiles',				'Bert OKeefe',					6,						2,						'2002-07-24 14:05:08'		),
						(		'goyette.shany@gmail.com',		'melyssa.thompson',			'Curt Sauer DDS',				2,						2,						'1976-01-10 02:03:51'		),
						(		'nschulist@gmail.com',			'vdickinson',				'Lillian Braun',				11,						3,						'2009-02-22 05:43:22'		),
						(		'marlee.hauck@ygmail.com',		'eugenia41',				'Esperanza West Sr.',			18,						4,						'1995-09-12 12:23:40'		),
						(		'leonel48@gmail.com',			'vbernier',					'Haleigh Kris III',				8,						2,						'1996-06-05 02:52:17'		),
						(		'clyde.white@gmail.com',		'kbartell',					'Fredy Lebsack',				9,						3,						'2012-07-23 09:37:51'		),
						(		'johns.arch@gmail.com',			'xschuppe',					'Aurelia Moen',					9,						4,						'1994-03-19 18:30:59'		),
						(		'duane71@gmail.com',			'dario26',					'Dr. Jermaine Wyman',			8,						2,						'1992-01-14 16:13:29'		),
						(		'marvin.lesch@gmail.com',		'awilkinson',				'Hilton O\'Keefe IV',			5,						3,						'2003-02-03 23:42:13'		),
						(		'dhamill@gmail.com',			'casper.easter',			'Kira Robel',					3,						4,						'2015-08-18 16:17:40'		),
						(		'batz.jailyn@gmail.com',		'jacques59',				'Eula Armstrong',				20,						4,						'2003-01-08 16:00:16'		),
						(		'ubailey@gmail.com',			'kattie.miller',			'Braeden Schaefer',				20,						3,						'2017-01-24 11:18:13'		),
						(		'walton.oconner@gmail.com',		'sbrekke',					'Mr. Cortez Doyle DVM',			13,						4,						'1982-04-09 00:11:46'		),
						(		'vjacobson@gmail.com',			'rhiannon.white',			'Elena Gerhold MD',				1,						2,						'2004-03-31 15:57:48'		),
						(		'delbert25@gmail.com',			'deonte36',					'Abby Olson',					10,						2,						'2006-07-27 15:14:07'		),
						(		'charley.walker@gmail.com',		'tamara78',					'Prof. Isadore OConner',		10,						2,						'1996-06-22 18:52:58'	);
INSERT INTO `account`	(		email,				 			username, 					fullname, 					department_id, 					created_date				)  
VALUES					( 		'nguyenhonghanh@gmail.com',		'nguyen.hoanghanh', 		'Hoang Hanh Nguyen',			1,								NOW()					),
						(		'pouros.leta@gmail.com',		'vincent41',				'Prof. Roberta Muller',			19,							'1991-06-24 14:05:42'		),
						(		'ozulauf@gmail.com',			'lucie.stamm',				'Maverick Murazik II',			19,							'2020-08-26 05:38:30'		),
                        (		'penelope09@gmail.com',			'mccullough.karl',			'Kimberly Heaney Sr.',			1,						    '2010-11-26 22:23:18'		);
    -- giá trị default muốn nhập vào bảng thì phải bỏ hẳn cột được thiết lập giá trị default đi
INSERT INTO `group`		( 			group_name, 										creator_id, 							created_date)
VALUES					(			'hội thích bóng đá',									13, 								'2019-09-09'),
						(			'hội du lịch',											11, 								'2019-01-01'),
                        (			'hội yêu ẩm thực',										5, 									'2018-08-05'),
                        (			'nhóm học tiếng Anh',									22, 								'2020-02-09'),
						(			'nhóm tiếng Hàn',										10, 								'2021-12-12'),
                        (			'Autem deserunt fuga sequi doloremque.',				6,							'2014-01-16 20:43:41'),
						(			'Dolore ut odit dolores voluptatem ipsa consequatur.',	6,							'1989-06-01 23:22:08'),
						(			'Dolor qui dolorem labore culpa aspernatur modi quos.',	29,							'2022-10-22 22:59:54'),
						(			'Repellat est natus reiciendis omnis dicta.',			3,							'2007-11-09 22:41:53'),
						(			'Dicta culpa et laudantium.',							9,							'1984-12-10 10:20:57'),
						(			'Similique optio qui et ut tempore eum.',				5,							'2023-02-04 00:28:42'),
						(			'Et error vel non voluptate repellat quae.',			28,							'1997-05-06 12:45:31'),
						(			'Et dolores et sapiente corporis et',					1,							'1989-10-07 07:42:14'),
						(			'Minima ab qui nam deserunt temporibus.',				3,							'2019-10-02 04:05:00'),
						(			'Rem sequi rerum cumque eos quia debitis illum.',		5,							'1992-02-02 12:38:31'),
						(			'Corrupti tenetur laborum sunt impedit in quia nisi.',	1,							'1985-07-16 18:59:39'),
						(			'Perferendis saepe et et esse vel.',					25,							'2018-07-10 01:07:52'),
						(			'Error non vero et itaque similique aut consequatur.',	3,							'1990-06-15 02:54:24'),
						(			'Officiis eum laborum ullam quidem ex.',				4,							'1977-06-27 02:59:21'),
						(			'Quam perferendis ut numquam suscipit nulla sed.',		4,							'1989-04-25 13:47:09'),
						(			'Dolores mollitia voluptas qui deserunt.',				1,							'1989-05-13 09:34:40'),
						(			'Quod dolorem aut necessitatibus',						1,							'2016-05-13 05:41:34'),
						(			'Doloribus aspernatur velit voluptas.',					4,							'1994-03-09 05:28:12'),
						(			'Nulla asperiores minus aut ex.',						4,							'2005-09-27 12:42:04'),
						(			'Dignissimos dolorum accusamus praesentium velit.',		4,							'2022-01-07 12:02:07'),
						(			'Ad numquam error aut labore.',							7,							'1984-08-11 13:09:06'),
						(			'Modi et et aliquam nulla error dolorem.',				10,							'2017-09-29 20:10:13'),
						(			'Cumque labore delectus doloremque',					9,							'2007-02-10 15:01:12'),
						(			'Fugit quia culpa magnam qui.',							12,							'1975-10-12 18:14:18'),
						(			'Amet ullam in qui aut cum sequi eos laborum.',			30,							'1976-06-12 19:57:00');
                        
INSERT INTO group_account		(group_id, 				account_id, 				join_date			)
VALUES							(	5, 						10,						'2021-12-30'		),
								(	2, 						17,						'2020-03-01'		),
								(	4, 						22,						'2018-08-05'		),
								(	10, 					13,						'2020-12-30'		),     
								(	2, 						3,						'2022-10-25'		),
                                (	10,						9,						'1999-02-11 13:56:27'),
								(	1,						13,						'1972-06-27 03:41:39'),
								(	30,						30,						'2018-10-07 16:03:39'),
								(	25,						4,						'2013-05-13 03:28:20'),
								(	28,						9,						'1979-03-31 01:52:49'),
								(	14,						3,						'2017-06-08 15:08:27'),
								(	7,						6,						'1975-06-08 22:37:26'),
								(	7,						10,						'2008-12-26 05:44:44'),
								(	11,						5,						'1981-09-18 16:33:18'),
								(	11,						8,						'2002-06-05 23:19:44'),
								(	17,						25,						'2015-07-07 08:12:49'),
								(	7,						11,						'2001-07-07 21:13:59'),
								(	29,						12,						'1980-08-27 01:27:33'),
								(	9,						3,						'2001-10-24 08:55:28'),
								(	18,						3,						'1980-01-18 23:18:31'),
								(	4,						19,						'2015-08-12 04:23:12'),
								(	9,						19,						'1988-06-12 20:45:57'),
								(	7,						15,						'1996-09-16 03:28:44'),
								(	9,						14,						'1998-09-24 12:51:21'),
								(	9,						10,						'2000-08-01 04:50:55'),
								(	18,						4,						'2017-07-01 01:50:13'),
								(	3,						5,						'1975-06-19 06:42:33'),
								(	6,						10,						'2000-04-09 09:35:13'),
								(	2,						11,						'2011-12-16 00:18:45'),
								(	15,						10,						'2005-10-07 09:37:23');
                                
INSERT INTO type_question	(type_question_name	)
VALUES						(		'Essay'						),
							(		'Muiltiple-Choice'			);
							
                            
INSERT INTO category_question	(category_name)
VALUES						
								( 'animi'		),
								( 'laudantium'	),
								( 'voluptas'	),
								( 'velit'		),
								( 'dolores'		),
								( 'culpa'		),
								( 'ut'			),
								( 'in'			),
								( 'magni'		),
								('dolore'		),
								('ad'			),
								('dolor'		),
								('sit'			),
								('aut'			),
								('ut'			),
								('rerum'		),
								('tempora'		),
								('velit'		),
								('tenetur'		),
								('ab'			),
								('quod'			),
								('inventore'	),
								('veritatis'	),
								('ab'			),
								('placeat'		),
								('dolores'		),
								('aspernatur'	),
								('atque'		),
								('molestiae'	),
								('sunt'			);
                                
INSERT INTO question	(		content,				 																																										type_question_id, 					category_id, 					creator_id, 			created_date		)
VALUES					
						( 'Ea dignissimos voluptatem eligendi voluptatibus. Odit non consequatur quae quia fuga aspernatur modi aspernatur.', 																							1,								 1,								10, 				'2008-12-05 21:18:47'),
						( 'Temporibus aut quam qui autem cumque et. Quo provident doloribus enim quia esse nulla. Qui voluptates ducimus corrupti nostrum impedit. Est voluptate qui ullam.', 											2, 								 2,								1,					'2018-08-11 15:31:30'),
						( 'Rerum rem consectetur dicta qui aut autem. Itaque similique ut veniam tempore atque recusandae.',																											1,								 3, 							20,					'1977-05-02 22:24:50'),
						( 'Dignissimos vero fugiat ducimus enim qui officiis officia consequuntur. Qui et ipsam consectetur id et. Ipsam in maxime deleniti numquam et et. Dignissimos velit ipsa nam at.',								2, 								 4, 							21,					'2019-07-21 11:25:09'),
						( 'Atque sint odit similique accusantium. Illum qui animi aut id.',					 																															1, 								 5, 							20,					'1981-09-14 09:30:26'),
						( 'Tempore sunt eum voluptatem voluptas. Minus reprehenderit nam praesentium ea est nemo nemo. Aperiam vel illo dolores sunt molestiae qui voluptate.',															1,								 6, 							11,					'2016-09-02 03:01:41'),
						( 'Quas optio accusantium hic itaque ut quasi qui. Accusantium perspiciatis minima veniam quis beatae sit facilis. Voluptatibus voluptatem eos error nobis qui. Aut eius optio et amet expedita.',				1, 								 7, 							11,					 '1991-12-16 17:22:58'),
						( 'Illo ipsam vel qui assumenda occaecati aut. Suscipit sint voluptatibus autem laboriosam recusandae repudiandae. Velit consectetur dicta occaecati voluptas quae. Et nesciunt qui inventore id.',				2,								 8, 							11,					 '1993-11-26 19:54:57'),
						( 'Accusantium sunt labore ut assumenda. Perferendis omnis sint nulla quisquam. Laborum maiores error mollitia ea aliquam aperiam harum. Corporis et culpa vitae cumque cum.',									1, 								 9, 							16,					 '2000-12-31 12:04:25'),
						( 'Nobis officiis expedita aut sit non qui. Sit amet asperiores quidem voluptatibus. Soluta accusamus ullam non architecto est.',																				2,								10, 							17,					 '1989-12-13 16:19:53'),
						( 'Ut voluptate ducimus dolorum sint aut. Et possimus quidem blanditiis ut aut. Vero itaque omnis cum incidunt corrupti.',																						1, 								11, 							18,				 	 '1989-12-10 11:52:51'),
						( 'Qui cumque error neque neque odio. Expedita temporibus doloremque sed. Et eius et quae esse quisquam ut omnis et. Expedita quo et cumque non rem temporibus quis.',											1, 								12, 							11,				 	 '1998-03-26 14:50:20'),
						( 'Molestias fuga quas a repellendus inventore ipsam enim cum. Omnis et consequatur velit earum ut. Adipisci minima magnam et quos sapiente.', 																	1, 								13, 							12,				 	 '2019-02-08 11:59:48'),
						( 'Enim ipsum tenetur ea molestiae voluptatum pariatur. Eum voluptatem quia sequi repudiandae dolores. Sint vel consectetur vitae voluptas. Molestiae magni deleniti ullam excepturi.', 						1, 								14, 							22,				 	 '1996-05-10 11:08:00'),
						( 'Inventore magnam quis quis necessitatibus debitis nihil illum magni. Qui quos assumenda et sed. Natus itaque velit rem perspiciatis.',																		1, 								15, 							25,					 '1976-12-31 00:11:50'),
						( 'Voluptatibus aut labore voluptatem non. Eos tenetur dolores facere. Ut consequatur illo iure aut unde impedit tempora. Soluta nostrum voluptatum aut odit.',													1, 								16, 							22,				 	 '2003-12-01 13:33:49'),
						( 'Iste et commodi rerum nihil error. Reprehenderit nostrum sunt voluptatem et laudantium dolorum. Eos doloribus earum iste dolores labore dignissimos.',														2, 								17, 							22,					 '2023-02-06 00:02:09'),
						( 'Qui voluptate suscipit illo repellat. Quae occaecati doloremque libero natus. Odio illum quas praesentium aut. Eum omnis veniam quas tenetur in eaque nobis.',												2, 								18, 							1,					 '1971-10-12 18:37:19'),
						( 'Praesentium quia temporibus voluptatem velit. Iste optio non excepturi rerum tempore quos. Aut magni laboriosam id corrupti autem.',																			2, 								19, 							5,					 '1980-06-27 06:19:09'),
						( 'Quia corrupti ipsam odit distinctio quos excepturi hic ut. Rerum ex et dignissimos voluptatem quis sint iste. Pariatur dolores ex sint enim et.',															1, 								20, 							1,					 '1982-04-17 13:32:10'),
						( 'Quibusdam et optio minima unde. Maiores quibusdam aliquid laboriosam ea quidem vel et. Sunt sapiente reprehenderit suscipit voluptatem sint voluptatibus et.',												2, 								21, 							2,					 '2015-12-29 11:38:15'),
						( 'Nam quod voluptatem quo non ea. Earum incidunt asperiores culpa odit veniam in iure omnis. Libero consequatur aliquid iste quod provident. Aut quo pariatur eius non ipsam et rerum.',						2, 								22, 							3,					 '2020-03-17 09:57:30'),
						( 'Et quae impedit qui in dicta est. Eligendi voluptatem reiciendis ut doloribus vitae atque.',																													2, 								23, 							4,					 '2002-06-18 08:09:35'),
						( 'Itaque et non dolore. Rerum expedita qui amet rem beatae omnis. Voluptatem dicta repellendus qui vero.',																										2, 								24, 							5,					 '1983-05-01 23:14:19'),
						( 'Hic est velit sed nemo. Quasi odio error rem adipisci. Repellat perferendis eos sapiente reiciendis. Autem vel eos incidunt voluptatibus sunt iste.',														2, 								25, 							6,					 '1986-06-15 10:47:53'),
						( 'Repudiandae ratione ipsum modi rem odit qui dolor. Et dolorem non aut recusandae saepe. Odio excepturi animi ut officiis. Qui ratione incidunt cupiditate nulla eaque.',										1, 								26, 							30,					 '2000-07-09 01:39:47'),
						( 'At aut corporis officia rem incidunt tempora. Et dignissimos est molestiae non natus temporibus. Vitae nam rerum nemo inventore voluptate. Est maiores expedita ipsam voluptatibus.',						1, 								27, 							12,					 '1985-07-28 22:20:05'),
						( 'Modi quibusdam ipsum perferendis ea saepe porro quod. Enim sint dolorem totam dolores molestiae et. Blanditiis fuga impedit asperiores odit. Dolorum blanditiis ipsa voluptatem repellat.',					1, 								28, 							13,					 '1986-11-20 08:18:27'),
						( 'Voluptatum in distinctio recusandae fugit quo. Molestias autem quia aut et. Perferendis et tempora aut consequuntur aut iusto velit. Et aut suscipit quod.',													1, 								29, 							15,					  '2020-04-06 23:17:00'),
						( 'Natus ab consequatur sint libero blanditiis ut porro. Tempora voluptatum nostrum sint tenetur ducimus voluptates aut. Numquam qui similique quas inventore hic facere.',										2, 								30, 							16,					  '1993-03-12 08:19:38');
                        
INSERT INTO answer		(				content, 																																												question_id, 								is_correct	)
VALUES					
						( 'Et nesciunt dolorem vel provident ut vero nesciunt cum. Voluptatem ipsum ipsam dolore dolores. Nam dolorum recusandae et repellat.',																		1, 											'1'),
						( 'Official illum illo voluptatem iusto non reiciendis fugiat. Accusantium consequuntur cum sit. Eum iste corporis dicta sit occaecati vero doloribus. In quis accusamus ducimus.',							2, 											'0'),
						( 'Est rem cumque tempore architecto. Odit eum non consectetur nam ipsum illo et. Excepturi ad veniam et quasi. Nemo consequatur rerum neque.',																3, 											'0'),
						( 'Vero sunt ipsam autem enim velit omnis architecto. Voluptate delectus placeat ipsa cupiditate nulla. Deserunt iusto voluptatem deserunt id. Quod voluptatem minus eaque nihil commodi aspernatur.', 		4, 											'0'),
						( 'Officiis enim tempore autem omnis debitis. Totam minus voluptas reprehenderit ut. Et ipsa esse hic laudantium.',																							5, 											'1'),
						( 'Repudiandae sunt enim nostrum eligendi cum. Totam esse quia dolorem quaerat aliquam laboriosam iste. Impedit ut impedit qui nisi facere fugiat nostrum. Non voluptas commodi odio ut.',					6, 											'0'),
						( 'Hic hic non inventore exercitationem atque vitae aperiam dolore. Maiores necessitatibus et itaque consequatur. Asperiores voluptate et necessitatibus.',													7, 											'0'),
						( 'Architecto est adipisci deserunt ut nostrum laborum error. Quae voluptas aut officiis laborum in. Sed expedita culpa eligendi sequi consequuntur.',														8, 											'0'),
						( 'Totam totam quae enim autem facilis fugit in. Sunt et nemo exercitationem aut ducimus facere vero laudantium.',																							9, 											'1'),
						( 'Nihil totam ratione aliquid sunt iste dolores hic. Expedita nihil voluptas voluptatem. Harum minus aut et quibusdam nam delectus perspiciatis aliquam. Consequatur culpa dolor maiores.',				10,											'1'),
						( 'Eum et qui ad eius. Enim similique ut est aliquam quidem occaecati quidem officia. Molestiae odio error consequatur voluptate iusto.',																	11,											'1'),
						( 'Deleniti eligendi qui nulla. In animi voluptates beatae in sit. Aut unde reprehenderit cumque sint. Quis laborum et consequatur odio natus et.',															12,											'1'),
						( 'Nam eos qui suscipit molestiae eveniet porro. Neque magnam voluptatem est odit non omnis. Magni quod vel temporibus deserunt et deserunt perspiciatis.',													13,											'1'),
						( 'Et recusandae dolores omnis veritatis et enim id. Ipsum eius rerum fugiat quia. Nesciunt labore non error illum laudantium corporis quis. Velit impedit illo porro et non.',								14,											'0'),
						( 'Aliquid veniam a perferendis. Quibusdam velit reprehenderit quaerat et repellat nam sit quibusdam. Vero sit quidem ratione molestiae suscipit impedit. Quas aliquid id iusto qui.',						15,											'0'),
						( 'Ullam corrupti harum et. Officiis quo eveniet suscipit deleniti est. Suscipit aut praesentium et et.',																									16,											'0'),
						( 'Doloremque sed at et et voluptate provident provident. Nam ut beatae natus tempore saepe. Sint reiciendis enim tempore. Error pariatur soluta est aliquid ut voluptates.',								17,											'0'),
						( 'Cum impedit nihil et sunt. Aperiam ut ipsum eveniet eius. Aut quibusdam dolorem architecto rerum optio libero itaque officia. Vel maiores nulla quae voluptatem debitis dolores.',						18,											'1'),
						( 'Qui ipsam aut laboriosam perferendis unde nisi non. Earum aliquam commodi est nihil adipisci. Laudantium aut et officia est enim. Quis architecto dicta ut repellendus sunt eaque iusto.',				19,											'0'),
						( 'Enim sunt facilis atque veritatis. Cum modi dolorum mollitia accusantium.',																																20,											'0'),
						( 'Molestiae fugit minima blanditiis non aut fuga omnis quibusdam. Voluptatibus et dicta eveniet voluptas aut blanditiis et. Minima sequi tempora aut. Qui est ut eos qui ullam.',							21,											'0'),
						( 'Illum accusantium aliquid quis explicabo velit. Aperiam minus aut hic fuga velit pariatur quae. Consequatur error eligendi necessitatibus non repudiandae vero.',										22,											'0'),
						( 'Enim voluptates quia nihil alias harum. Maiores accusamus corrupti deleniti architecto minima. Eum dignissimos esse reprehenderit culpa. Nihil accusantium et repellat quasi voluptatem.',				23,											'0'),
						( 'Iure porro cupiditate magni aut necessitatibus impedit recusandae. Laboriosam neque officia voluptatem.\nEa sapiente officia nobis quia numquam. Quo ea ex nisi laborum.',								24,											'1'),
						( 'Non laborum repudiandae delectus sit est. Ut at alias blanditiis nemo quidem est cupiditate sapiente. Voluptatem beatae nulla rerum.',																	25,											'0'),
						( 'Nihil vitae modi aut ab. Ut et iste porro. Et reiciendis fuga et.',																																		26,											'0'),
						( 'Eum id similique et dicta deserunt. Et modi est nam ea. Aut ducimus consequuntur rem. Omnis perferendis necessitatibus quia numquam voluptas voluptates odit aliquam.',									27,											'1'),
						( 'Sint iste vero dolorum quo quia ipsam. Vel culpa occaecati possimus architecto sed quo impedit eligendi. Magnam est qui non magni. Eligendi possimus porro dolor porro.',								28,											'1'),
						( 'Ullam fugiat aut ut. Tenetur dolor voluptate eligendi necessitatibus nisi aut. Quia porro nesciunt ut rem eligendi. Itaque quia molestias eum nostrum sit. Dicta architecto repellendus nam qui.',		29,											'0'),
						( 'Totam aperiam harum deserunt. Veniam eius rerum repellat distinctio veniam est labore. Ea asperiores nostrum dolore. Eum et fugit autem ratione officiis.',												30,											'1');
                     
INSERT INTO exam			(`code`,				 	title, 																			category_id, 		duration, 			creator_id, 			created_date    )
VALUES					
							('N3', 					'Neque ad non ducimus.', 															2, 					60, 				10,					'1982-10-02 21:01:13'),
							('N9', 					'Saepe vel pariatur velit in dignissimos.',											4, 					90,					21,					'1998-03-03 19:52:06'),
							('N4', 					'Ipsa iusto sint a dicta reprehenderit occaecati nemo aperiam.',					6, 					120, 				11,					'1978-01-11 15:52:37'),
							('N1', 					'Ut est veniam labore doloremque.',													8, 					120,				16,					'1986-05-30 08:16:46'),
							('N10',					'Nihil tempore quisquam unde voluptas vel fuga ipsum iste.',						9, 					90, 				18,					'2010-05-24 15:50:22'),
							('N15',					'Recusandae dolor vel eos doloribus sapiente.',										14,					60,					22,					'1984-03-23 23:48:20'),
							('N16',					'Non at iusto at nisi fuga.',														21,					60,					13,					'2007-12-18 15:55:16'),
							('N17',					'Vitae non et officia.',															23,					90,					16,					'1986-04-09 23:22:39');
                        
INSERT INTO exam_question		(exam_id,	question_id	)
VALUES							
									(1, 		1),
									(1, 		9),
									(1, 		17),
									(1, 		25),
									(2, 		2),
									(2, 		10),
									(2, 		18),
									(2, 		26),
									(3, 		3),
									(3, 		11),
									(3, 		19),
									(3, 		27),
									(4, 		4),
									(4, 		12),
									(4, 		20),
									(4, 		28),
									(5, 		5),
									(5, 		13),
									(5, 		21),
									(5, 		29),
									(6, 		6),
									(6, 		14),
									(6, 		22),
									(6, 		30),
									(7, 		7),
									(7, 		15),
									(7, 		23),
									(8, 		8),
									(8, 		16),
									(8, 		24);      
                                
                                
